# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.TextField(max_length=250),
        ),
    ]
